# test ART advancement

setup :
	---
	type : world
	name : TEST
	sector : 66
	marker : 1K
	adv :
		art
		art
		infrastructure
start :
	---
	to : hand
	type : tech
	name : TEST
	adv :
		art
		computation
		computation
	---
	to : hand
	type : world
	name : TEST
	adv :
		art
		computation
		computation
	---
	to : colony
	type : world
	sector : 22
	name : TEST
	adv :
		art
		art
		art
	---
	to : homeworld
	type : tech
	name : TEST
	adv :
		art
		art
		art
