# test BATTLE action

setup :
	---
	to : colony
	type : world
	name : TEST
	sector : 25
	adv :
		weapons
		machinery
		diplomacy
	---
	to : homeworld
	type : tech
	name : TEST
	adv :
		military
		defense
		military
	---
	type : world
	sector : 22
	adv : military
	---
	type : galaxy
	sector : 25
	n : 2
	camp : player
	---
	type : galaxy
	sector : 23
	n : 2
	camp : neutral
	---
	type : galaxy
	sector : 24
	n : 3
	camp : neutral
start:
	---
	type : blank
	suit : H
