setup :
	---
	type : civ
	name : TEST
	sector : 11
	era : 1
	world : NOWORLD
	victory : territory
	advancement : K
	tech :
		NONAME1
		NONAME2
		NONAME3
	---
	type : galaxy
	sector : 22
	n : 4
	camp : player
	---
	type : galaxy
	sector : 23
	n : 4
	camp : player
	---
	type : galaxy
	sector : 24
	n : 4
	camp : player
	---
	type : galaxy
	sector : 26
	n : 2
	camp : neutral
start:
	---
	type : civ
	name : TEST
	sector : 22
	era : 1
	suit : S
	world : NOWORLD
	victory : territory
#	victory : culture
	advancement : M
	tech :
		NONAME1
		NONAME2
		NONAME3
	---
	type : civ
	name : TEST
	sector : 33
	era : 1
	suit : S
	world : NOWORLD
	victory : population
	advancement : H
	tech :
		NONAME1
		NONAME2
		NONAME3
