# test no world initial

setup :
	---
	type : drop		# drop hands
	---
	type : blank	# add 6 blank card
	---
	type : blank
	---
	type : blank
	---
	type : blank
	---
	type : blank
	---
	type : blank
start :
	---
	to : colony
	type : world
	---
	to : colony
	type : world
	---
	to : colony
	type : world
	---
	to : colony
	type : world
	---
	to : colony
	type : world
	---
	to : colony
	type : world
	---
	to : colony
	type : world
	---
	to : colony
	type : world
	---
	to : colony
	type : world
