image : hex
width : 100
height : 86
name :
	position : absolute
	top : 60%
	left : 20%
	width : 60%
	height : 40%
	text : hex.name
	color : 0x202040
	size : 10
	text_align : C
	env : content
people :
	position : absolute
	width : 100%
	height : 100%
	text : hex.people
	env : content
	size : 16
	text_align : C
id :
	position : absolute
	left : 28%
	height : 20
	width : 100%
	top : 3
	text : hex.id
	size : 12
