name: Nightly Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Website
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build Soluna
        uses: ./soluna/.github/actions/soluna
        id: build
        with:
          soluna_path: "./soluna"
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Build Website
        shell: bash
        working-directory: website
        env:
          SITE_BASE: /deepfuture/
          SOLUNA_JS_PATH: ${{ steps.build.outputs.SOLUNA_JS_PATH }}
          SOLUNA_WASM_PATH: ${{ steps.build.outputs.SOLUNA_WASM_PATH }}
          SOLUNA_WASM_MAP_PATH: ${{ steps.build.outputs.SOLUNA_WASM_MAP_PATH }}
        run: |
          corepack enable
          pnpm install --no-frozen-lockfile
          pnpm run build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: website/dist/
  deploy:
    name: Deploy to GitHub Pages
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
